AWSTemplateFormatVersion: 2010-09-09
Description: Provision Nat Gateway for our Private Subnets
Parameters:
  ProjectName:
    Description: Project stack is been applied to.
    Type: String
  EnvironmentName:
    Description: Environment context we are working on.
    Type: String
Resources:
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGateWayVPCAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-NatGatewayEIP1

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGateWayVPCAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-NatGatewayEIP2
  
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId 
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-NatGatewayA

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId 
      SubnetId: !Ref PublicSubnetB
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-NatGatewayB

  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: !Ref PublicCIDR
      NatGatewayId: !Ref NatGateway1

  DefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: !Ref PublicCIDR
      NatGatewayId: !Ref NatGateway2
